"""Type stub for the compiled crp_telemetry extension (Rust/PyO3).

This is the FROZEN Tier-0 telemetry API for M3-M4 (spec: Phase 0 design,
ADR-005). Changes require a defect correction or an RFC.
"""

class Telemetry:
    def __init__(self, capacity: int) -> None: ...
    def record(self, kind: int, tensor_id: int, value: float) -> bool: ...
    def drain(self, max: int) -> list[tuple[int, int, int, float]]: ...
    def dropped(self) -> int: ...
    def __len__(self) -> int: ...
