"""
builders.py — Output Scaffolding and Next-Step Suggestions for Agent OS

Extracted from workflow.py to give the build/generate cluster its own module.
Handles creating concrete file artifacts (skill .md files, Flutter screens)
and computing the "what to do next" suggestions list.

Usage:
    from builders import build_output, suggest_actions, _next_steps_for
"""

import json
import re
from datetime import datetime
from pathlib import Path


# ── Next-step suggestion generator ───────────────────────────────────────────

def _next_steps_for(output_type: str, result, intent: dict) -> list:
    """
    Return a list of next-step strings tailored to the output type.

    Args:
        output_type: "skill" | "app" | "audio" | "video" | other
        result:      WorkflowResult instance
        intent:      Parsed intent dict from analyze_prompt*()
    """
    topic = intent["topic"]
    slug  = re.sub(r"[^a-z0-9]+", "-", topic.lower()).strip("-")

    if output_type == "skill":
        return [
            f"Create skill: `skills/{slug}/SKILL.md`",
            "Add trigger phrase to CLAUDE.md",
            "Test with /graphify and verify output",
        ]
    elif output_type == "app":
        return [
            f"Add Flutter screen: `lib/{slug.replace('-', '_')}_screen.dart`",
            f"Add server endpoint: POST /workflow/{slug}",
            "Wire up to Agent OS action buttons",
        ]
    elif output_type == "audio" and result.audio_path:
        audio_name = Path(result.audio_path).name
        return [
            f"hermes load {audio_name}",
            "Generate avatar video with Hermes",
            "Save video to asset_library/",
        ]
    elif output_type == "video":
        return [
            "Get audio overview first (run with --browser)",
            "Load into Hermes for avatar generation",
            "Publish to DAAVA pipeline",
        ]
    else:
        return [
            f"Review note: Workflow: {topic}",
            "Link to related Obsidian notes",
            "Move from 00-Inbox to 01-Projects when processed",
        ]


# ── Build dispatcher ──────────────────────────────────────────────────────────

def build_output(intent: dict, result) -> list:
    """
    CDLC Phase: GENERATE (artifacts)
    Scaffold the requested output type when possible without a browser.

    - "skill": scaffold a skill .md file via _scaffold_skill()
    - "note":  already handled by save_to_obsidian() in workflow.py
    - "app":   generate Flutter screen scaffold via _scaffold_flutter_screen()
    - others:  return empty list (manual steps required)

    Args:
        intent: Parsed intent dict (topic, output_type, action, keywords, tags)
        result: WorkflowResult instance (for notebook/audio context in skill)

    Returns:
        list of built-artifact dicts, e.g. [{"type": "skill", "path": "..."}]
    """
    built = []
    output_type = intent["output_type"]
    topic       = intent["topic"]
    slug        = re.sub(r"[^a-z0-9]+", "-", topic.lower()).strip("-")

    if output_type == "skill":
        built.extend(_scaffold_skill(topic, slug, intent, result))
    elif output_type == "app":
        built.extend(_scaffold_flutter_screen(topic, slug))

    return built


# ── Skill scaffolder ──────────────────────────────────────────────────────────

def _scaffold_skill(topic: str, slug: str, intent: dict, result) -> list:
    """
    Generate a skill .md file from the workflow content.

    Creates the file at: agent_os/generated_skills/<slug>.md
    Includes NotebookLM source link and audio path if available.

    Returns:
        [{"type": "skill", "path": str, "name": slug}]
    """
    skills_output = Path(__file__).parent / "generated_skills"
    skills_output.mkdir(exist_ok=True)

    skill_path = skills_output / f"{slug}.md"

    notebook_ref = ""
    if result.notebook:
        nb_title = result.notebook.get("title", "")
        nb_url   = result.notebook.get("url", "")
        notebook_ref = f"\n## Source\n- NotebookLM: [{nb_title}](https://notebooklm.google.com{nb_url})"

    audio_ref = ""
    if result.audio_path:
        audio_ref = f"\n## Audio Overview\n- File: `{result.audio_path}`"

    skill_content = f"""---
name: {slug}
description: >
  {topic}. Auto-generated by Agent OS workflow on {datetime.now().strftime('%Y-%m-%d')}.
  Trigger: /{slug}
tags: {json.dumps(intent.get('tags', []))}
---

# {topic}

> Auto-generated skill from Agent OS workflow pipeline.
> Source: NotebookLM notebook + Obsidian capture.
> Review and enrich before deploying.

## Purpose
{intent.get('action', 'summarize').title()} content about: **{topic}**

## When to Use
- User asks about {topic}
- User invokes `/{slug}`
- Related to: {', '.join(intent.get('keywords', []))}

## Key Content
<!-- TODO: Paste key content from your NotebookLM notebook here -->
<!-- Use the audio overview transcript or studio study guide -->

## Workflow
1. Load relevant Obsidian notes with `/context`
2. Apply this skill for domain-specific guidance
3. Save any new insights with `/save`
{notebook_ref}
{audio_ref}

## Integration Points
- Agent OS: `agent_os.py cmd_{slug.replace('-', '_')}()`
- Flutter: Add panel in `agent_os_screen.dart`
- Obsidian: Tag notes with `#{slug}`
"""

    skill_path.write_text(skill_content, encoding="utf-8")
    print(f"[Workflow] ✓ Skill scaffolded: {skill_path}")
    return [{"type": "skill", "path": str(skill_path), "name": slug}]


# ── Flutter screen scaffolder ─────────────────────────────────────────────────

def _scaffold_flutter_screen(topic: str, slug: str) -> list:
    """
    Generate a Flutter screen scaffold for a new Agent OS topic view.

    Creates the file at: learning_dashboard_app/lib/<slug>_screen.dart
    The generated screen includes a loading state, HTTP TODO comment,
    and the Nth Dimension visual theme (green accent, Lexend font).

    Returns:
        [{"type": "flutter_screen", "path": str, "class": ClassName}]
        or [] if the Flutter lib directory doesn't exist.
    """
    output_dir = Path(__file__).parent.parent / "learning_dashboard_app" / "lib"
    dart_name  = slug.replace("-", "_") + "_screen.dart"
    class_name = "".join(w.title() for w in slug.split("-")) + "Screen"
    screen_path = output_dir / dart_name

    if not output_dir.exists():
        print(f"[Workflow] Flutter lib dir not found: {output_dir}")
        return []

    dart_content = f"""import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

// Auto-generated by Agent OS workflow: {datetime.now().strftime('%Y-%m-%d')}
// Topic: {topic}
// TODO: Wire up to Agent OS server endpoint

class {class_name} extends StatefulWidget {{
  const {class_name}({{super.key}});

  @override
  State<{class_name}> createState() => _{class_name}State();
}}

class _{class_name}State extends State<{class_name}> {{
  bool _loading = false;
  String _content = '';

  @override
  void initState() {{
    super.initState();
    _load();
  }}

  Future<void> _load() async {{
    setState(() => _loading = true);
    // TODO: call http://localhost:8765/workflow/{slug}
    await Future.delayed(const Duration(milliseconds: 500));
    setState(() {{
      _content = 'Content for {topic} — wire up to Agent OS server.';
      _loading = false;
    }});
  }}

  @override
  Widget build(BuildContext context) {{
    return Scaffold(
      backgroundColor: const Color(0xFFF6F8F6),
      appBar: AppBar(
        title: Text('{topic}',
            style: GoogleFonts.lexend(fontWeight: FontWeight.bold)),
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: _loading
          ? const Center(child: CircularProgressIndicator(color: Color(0xFF13EC5B)))
          : SingleChildScrollView(
              padding: const EdgeInsets.all(24),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Container(
                    padding: const EdgeInsets.all(20),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(16),
                      boxShadow: [BoxShadow(
                        color: Colors.black.withOpacity(0.04),
                        blurRadius: 8,
                      )],
                    ),
                    child: Text(_content,
                        style: GoogleFonts.lexend(fontSize: 14)),
                  ),
                ],
              ),
            ),
    );
  }}
}}
"""

    screen_path.write_text(dart_content, encoding="utf-8")
    print(f"[Workflow] ✓ Flutter screen: {screen_path}")
    return [{"type": "flutter_screen", "path": str(screen_path), "class": class_name}]


# ── Suggest next actions ──────────────────────────────────────────────────────

def suggest_actions(intent: dict, result) -> list:
    """
    CDLC Phase: OBSERVE
    AutoResearch loop output: what to build/run next.
    These suggestions feed back into the next workflow run (BIT Tune).

    Returns a list of suggestion dicts with keys: action, description, command, priority.
    """
    suggestions = []
    output_type = intent["output_type"]
    topic       = intent["topic"]
    slug        = re.sub(r"[^a-z0-9]+", "-", topic.lower()).strip("-")

    if output_type == "skill" and not any(b["type"] == "skill" for b in result.built):
        suggestions.append({
            "action":      "Build Skill",
            "description": f"Scaffold Agent OS skill file for '{topic}'",
            "command":     f'python workflow.py "{intent["prompt"]}" --build',
            "priority":    "high",
        })

    if result.audio_path:
        suggestions.append({
            "action":      "Generate Video",
            "description": "Load captured audio into Hermes for avatar video",
            "command":     f"python agent_os.py hermes load {Path(result.audio_path).name}",
            "priority":    "high",
        })
    elif result.notebook and output_type in ("audio", "video"):
        suggestions.append({
            "action":      "Capture Audio",
            "description": "Open NotebookLM and capture audio overview",
            "command":     f'python workflow.py "{intent["prompt"]}" --browser',
            "priority":    "high",
        })

    suggestions.append({
        "action":      "Refresh Cache",
        "description": "Scrape all 261 notebooks fresh (takes ~2 min)",
        "command":     "python notebooklm_agent.py list",
        "priority":    "low",
    })

    suggestions.append({
        "action":      "Add to Agent OS",
        "description": f"Add '{topic}' as a workflow shortcut in agent_os.py",
        "command":     f"python agent_os.py save '{topic}' workflow",
        "priority":    "medium",
    })

    return suggestions
